export const CourseTypes = ["CONFERENCE", "COURSE", "SUBSCRIPTION", "BOOK"];

export const SubjectTypes = [
    "PROGRAMMING_LANGUAGES",
    "WEB_DEVELOPMENT",
    "MOBILE_DEVELOPMENT",
    "DATA_SCIENCE",
    "SOFTWARE_ENGINEERING",
    "DATABASES",
    "CYBERSECURITY",
    "GRAPHIC_DESIGN",
    "BUSINESS_DEVELOPMENT",
    "LANGUAGE_STUDIES"
];

export const ExpenseType = [
	"ACCOMMODATION",
	"TRANSPORT",
	"OTHER"
]